FROM mcr.microsoft.com/devcontainers/go:1-1.25-trixie
RUN apt update && export DEBIAN_FRONTEND=noninteractive \
    && apt -y install ffmpeg libavutil-dev libavformat-dev libfribidi-dev libharfbuzz-dev
