ARG UBUNTU_VERSION
FROM docker.io/ubuntu:${UBUNTU_VERSION} AS builder

ARG TARGET

COPY build/image /
ENV KARABERUS_LISTEN_HOST=0.0.0.0
ENV KARABERUS_UI_DIST_DIR="/usr/local/share/karaberus/ui_dist"
ENV LD_LIBRARY_PATH="/usr/local/lib/${TARGET}:/usr/local/lib:${LD_LIBRARY_PATH}"
EXPOSE 8888
ENTRYPOINT ["karaberus"]
